### PR TITLE
Fix for next@9.4.0

### LINKED ISSUE #53: Next.js 9.4 breaking error
Hey 👋 @jescalan , I'm back with another problem that I encountered after upgrading to Next.js 9.4. I've managed to reproduce the issue [here](https://github.com/jensmeindertsma/issue-next-mdx-enhanced-2). This is really a basic setup, a `create-next-app` project where I've installed `next-mdx-enhanced` and `babel-plugin-import-glob-array`. This causes the following error: 
```
Attempted import error: 'frontMatter' is not exported from 'C:\dev\issue-next-mdx-enhanced-2\pages\blog\test.mdx' (imported as '_iga').
Could not find files for /blog in .next/build-manifest.json
```
After looking through the 9.4 changelog, I believe this is caused by the new React Refresh, although I'm not certain at all? It might be caused by the absolute path imports? 

This repository also contains branch `next-9.3` where I've downgraded to Next.js 9.3.6, and this works fine. 
Could you please investigate this? This prevents everyone from using Next.js 9.4.

### PR DESCRIPTION
**Pull request by jescalan**
Nextjs made a change to the way that babel plugins are added to the client side bundle, which caused this plugin to work for the server but not client bundles. This was a very weird error, but it should be worked out now.

Interestingly, this was a case that was not caught by our tests, which compare the server-rendered output and don't test with javascript active after hydration. It mat be worth adding a test where everything is evaluated after hydrating in the future, I have one in next-mdx-remote.

Closes #53

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -42,25 +42,36 @@ module.exports = (pluginOptions = {}) => (nextConfig = {}) => {
...
+                babelPluginFrontmatter(options, pluginOptions)
+              )
+            }
+            // and this is server
+          } else if (rule.use.loader === 'next-babel-loader') {
+            if (!rule.use.options.plugins) rule.use.options.plugins = []
+            rule.use.options.plugins.push(
+              babelPluginFrontmatter(options, pluginOptions)
+            )
+          }
```
Comment (pruett) [inline index.js:74]: 🤯
